name: tutility
publish_to: "none"
version: 1.2.4+14

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.1
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.0.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  json_annotation: ^4.5.0
  package_info_plus: ^6.0.0
  shared_preferences: ^2.0.15
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_appbar.svg
    - assets/get_timetable.js

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_adaptive.png"
