name: tutility
publish_to: 'none'
version: 1.2.0+10

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.1+1
  http: ^0.13.4
  json_annotation: ^4.5.0
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_appbar.svg
    - assets/get_timetable.js

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon_adaptive.png'
